config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:show, :new, :create]
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  # has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail_id, :ingredient_id, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
    redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:ingredient_id, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>Fancy cocktails</h1>
<!-- <ul>
  <% @cocktails.each do |cocktail| %>
  <li> <%= link_to cocktail.name, cocktail_path(cocktail) %>
    <% if cocktail.photo.attached?  %>
    <%= cl_image_tag cocktail.photo.key, height: 20, width: 30, crop: :fill %>
    <% end %>
  </li>
  <% end %>
</ul> -->

<ul>
  <% @cocktails.each do |cocktail| %>
  <li> <%= link_to cocktail.name, cocktail_path(cocktail) %>
  </li>
  <% end %>
</ul>

<%= link_to "Create a new cocktail", new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>Create a new cocktail</h1>

<!-- <div class="row  justify-content-center">
  <div class="col-6">
    <%= simple_form_for(@cocktail) do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit %>
    <% end %>
  </div>
</div> -->

<div class="row  justify-content-center">
  <div class="col-6">
    <%= simple_form_for(@cocktail) do |f| %>
      <%= f.input :name %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<!-- <div class="d-flex align-content-center">
  <h1> <%= @cocktail.name %></h1>
  <div class="d-flex align-content-center">
    <% if @cocktail.photo.attached?  %>
        <%= cl_image_tag @cocktail.photo.key, height: 20, width: 30, crop: :fill %>
    <% end %>
    <ul>
    <% @cocktail.doses.each do |dose| %>
      <li> <%= dose.ingredient.name %> <%= link_to cocktail_dose_path(dose), method: :delete do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      </li>
    <% end %>
    </ul>
    <%= link_to new_cocktail_dose_path(@cocktail) do %>
      <button class="btn btn-primary">Add a new dose</button>
    <% end %>
    <%= link_to cocktails_path do %>
      <button class="btn btn-primary">Back to Cocktail list</button>
    <% end %>
  </div>
</div> -->

<div class="d-flex align-content-center">
  <h1> <%= @cocktail.name %></h1>
  <div class="d-flex align-content-center">
    <ul>
    <% @cocktail.doses.each do |dose| %>
      <li> <%= dose.ingredient.name %> <%= link_to cocktail_dose_path(dose), method: :delete do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      </li>
    <% end %>
    </ul>
    <%= link_to new_cocktail_dose_path(@cocktail) do %>
      <button class="btn btn-primary">Add a new dose</button>
    <% end %>
    <%= link_to cocktails_path do %>
      <button class="btn btn-primary">Back to Cocktail list</button>
    <% end %>
  </div>
</div>

app/views/doses/new.html.erb
<h1>Add a new dose</h1>

<%= simple_form_for [ @cocktail, @dose ] do |f| %>
  <%= f.association :ingredient, include_hidden: false, as: :select %>
  <%= f.input :description %>
  <%= f.submit "Add ingredient" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>